# Compass Config
preferred_syntax = :sass
http_path = '/'
css_dir = 'static/css'
sass_dir = 'app/scss'
images_dir = 'static/imgs'
fonts_dir = 'static/fonts'
relative_assets = true
line_comments = true
